---
engines:
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E401:
        enabled: false
  watson:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
exclude_paths:
- Toontown Empire/src/build/**/*
- Toontown Empire/src/dependencies/**/*
