language: python
sudo: require
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
 # - "pypy"
# command to install dependencies
before_script:
  - git clone https://github.com/Astron/panda3d
  - sudo apt-get update
  - sudo apt-get install python-dev libpng-dev zlib1g-dev libssl-dev libx11-dev libgl1-mesa-dev libxrandr-dev libxxf86dga-dev libxcursor-dev bison flex libfreetype6-dev libvorbis-dev libjpeg-dev libopenal-dev libode-dev nvidia-cg-toolkit git 
  - cd panda3d
  - python2.7 makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2 --threads 6
  - sudo python2.7 makepanda/installpanda.py
  - sudo ldconfig
  - cd ..
  - cd "Toontown Empire/src/tools"
  - /usr/bin/python2 -m prepare_client  --distribution en --build-dir build --src-dir .. --server-ver TTE-1.0 --build-mfs --resources-dir ../../resources --include NonRepeatableRandomSourceUD.py --include NonRepeatableRandomSourceAI.py --exclude ServiceStart.py
# command to run tests
script: /usr/bin/python2 -m build_client_linux
notifications:
  irc:
    channels:
      - "chat.freenode.net#toontownempire"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
